language: node_js
node_js:
#  - "4"
#  - "6"
  - "8"
script: npm run $COMMAND
env:
  - COMMAND=lint
  - COMMAND=test
  - COMMAND=test:karma-travis
  - COMMAND=build
before_install:
  - "npm set legacy-bundling=true"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
